### ISSUE TITLE
[Bug]: Program terminated due to unhandled exception

### ISSUE THREAD

**Issue by LiberiFatali** [vzhd1701/gridplayer#113]
### GridPlayer version

0.4.3

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 20.04

### What distribution channel are you using? [LINUX ONLY]

AppImage

### Bug description

When adding more videos to the running playlist (using right click --> Add Files), Gridplayer crashed. 

Then it shows below exception

### Log excerpt

```
Traceback (most recent call last):
  File "/tmp/.mount_GridPlID6YyY/opt/python3.9/lib/python3.9/site-packages/gridplayer/player/managers/base.py", line 24, in eventFilter
    return event_function(event) is True
  File "/tmp/.mount_GridPlID6YyY/opt/python3.9/lib/python3.9/site-packages/gridplayer/player/managers/drag_n_drop.py", line 39, in mouseMoveEvent
    if self._is_drag_started(event):
  File "/tmp/.mount_GridPlID6YyY/opt/python3.9/lib/python3.9/site-packages/gridplayer/player/managers/drag_n_drop.py", line 113, in _is_drag_started
    if not event.buttons() & Qt.LeftButton:
AttributeError: 'QContextMenuEvent' object has no attribute 'buttons'
```

**Comment by LiberiFatali** [comment]
closed as cannot reproduce anymore
