### ISSUE TITLE
[Bug]: Can't open the exe file

### ISSUE THREAD

**Issue by mikehendry** [vzhd1701/gridplayer#127]
### GridPlayer version

0.5.0

### What OS are you using?

Windows

### OS Version / Linux distribution

win11

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

open error

### Log excerpt

```shell
2023-05-18 15:09:23,883 (14228) | gridplayer.main.init_translator | WARNING | Failed to load QT translation for zh_CN
2023-05-18 15:09:24,202 (14228) | UNHANDLED | CRITICAL | Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\__main__.py", line 40, in <module>
  File "gridplayer\__main__.py", line 29, in main
  File "gridplayer\main\run.py", line 34, in run_app
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\player.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\managers\active_block.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\widgets\video_block.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\url_resolve.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\resolver_base.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\api.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\session.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'

2023-05-18 15:11:43,937 (21588) | gridplayer.main.init_translator | WARNING | Failed to load QT translation for zh_CN
2023-05-18 15:11:44,180 (21588) | UNHANDLED | CRITICAL | Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\__main__.py", line 40, in <module>
  File "gridplayer\__main__.py", line 29, in main
  File "gridplayer\main\run.py", line 34, in run_app
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\player.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\managers\active_block.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\widgets\video_block.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\url_resolve.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\resolver_base.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\api.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\session.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'

2023-05-18 15:12:14,185 (20796) | gridplayer.main.init_translator | WARNING | Failed to load QT translation for zh_CN
2023-05-18 15:12:14,939 (20796) | UNHANDLED | CRITICAL | Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\__main__.py", line 40, in <module>
  File "gridplayer\__main__.py", line 29, in main
  File "gridplayer\main\run.py", line 34, in run_app
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\player.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\managers\active_block.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\widgets\video_block.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\url_resolve.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\resolver_base.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\api.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\session.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'
```

**Comment by sum1game** [comment]
When I open the exe program, it also prompts such an error

OS Version / Linux distribution
win10

`Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\__main__.py", line 40, in <module>
  File "gridplayer\__main__.py", line 29, in main
  File "gridplayer\main\run.py", line 34, in run_app
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\player.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\managers\active_block.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\widgets\video_block.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\url_resolve.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\resolver_base.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\api.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\session.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'
`

**Comment by sum1game** [comment]
Tested both programs, same result
[GridPlayer-0.5.0-win64-install.exe]
[GridPlayer-0.5.0-win64-portable.zip]

**Comment by sum1game** [comment]
Tested both programs, same result
[GridPlayer-0.5.0-win64-install.exe]
[GridPlayer-0.5.0-win64-portable.zip]

Version 0.4.3 is running normally

**Comment by vzhd1701** [comment]
Working on it

**Comment by vzhd1701** [comment]
Binaries are now rebuilt. Please re-download them and try again.

**Comment by sum1game** [comment]
> Binaries are now rebuilt. Please re-download them and try again.

The 0.5 exe can run normally now. Thank you for fixing it.
