### ISSUE TITLE
[Bug]: No module named 'charset_normalizer.md'

### ISSUE THREAD

**Issue by SerkanES** [vzhd1701/gridplayer#131]
### GridPlayer version

0.5

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 11

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\__main__.py", line 40, in <module>
  File "gridplayer\__main__.py", line 29, in main
  File "gridplayer\main\run.py", line 34, in run_app
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\player.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\player\managers\active_block.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\widgets\video_block.py", line 36, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\url_resolve.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "gridplayer\utils\url_resolve\resolver_base.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\__init__.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\api.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "streamlink\session.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md'

**Comment by vzhd1701** [comment]
Please re-download the binary from the [release page](https://github.com/vzhd1701/gridplayer/releases/tag/v0.5.0).
