### ISSUE TITLE
Oups sorry, the problem of the last year resurfaced in https://my.mail.ru/

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#181]
### GridPlayer version

0.5.3

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10 last version 

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Hello, sorry really to make the same request of the last year and we thank you so much ta have fix the bug.....and recently, thise site seems to make strong protections.....

 I use this site because my favorite streaming site posts its videos on this site and I would like to play the videos without a heavy web browser especially since my laptop is a bit old and media player allows us to fully buffer the video which is ideal when the wifi becomes weak at night.....

I noticed this bug with the site my.mail.ru with other media players that use yt-dlp.....this site seems to change its protection frequently, but we can download from this site via yt-dlp but unable to play streaming video in media players from this famous r web site.....

https://my.mail.ru/v/sienduk/video/35/707.html

### Log excerpt

```shell
2023-10-17 21:40:04,056 (9372) | VideoURLResolverWorker | error | URL resolver exception
Traceback (most recent call last):
  File "gridplayer\utils\url_resolve\url_resolve.py", line 51, in resolve
  File "gridplayer\utils\url_resolve\url_resolve.py", line 71, in resolve_url
  File "gridplayer\utils\url_resolve\resolver_base.py", line 41, in resolve
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 57, in streams
  File "functools.py", line 967, in __get__
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 45, in is_live
  File "gridplayer\utils\url_resolve\stream_detect.py", line 56, in is_http_live_stream
  File "streamlink\plugin\api\http_session.py", line 190, in request
streamlink.exceptions.PluginError: Unable to open URL: http://cdn59.my.mail.ru/hv/73478144.mp4?slave[]=s%3Ahttp%3A%2F%2F10.146.243.1%3A8003%2Frados3%2F73478144-hv&p=f&expire_at=1697587200&touch=1637861346&reg=216&sign=1161dd030875f64b2f643b12d4e040eb426d02c7 (403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/73478144.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2F10.146.243.1%3A8003%2Frados3%2F73478144-hv&p=f&expire_at=1697587200&touch=1637861346&reg=216&sign=1161dd030875f64b2f643b12d4e040eb426d02c7)
2023-10-17 21:42:06,300 (9372) | VideoBlock | debug | Closing video block 14c3637a466a5511
2023-10-17 21:42:06,301 (9372) | VideoBlock | debug | 14c3637a466a5511: cleaning up resolver
2023-10-17 21:42:06,301 (9372) | VideoBlock | debug | 14c3637a466a5511: cleaning up driver 
2023-10-17 21:42:06,302 (9372) | VideoBlock | debug | 14c3637a466a5511: cleaning up done
2023-10-17 21:42:06,304 (9372) | VideoBlocksManager | debug | Clearing video blocks array
2023-10-17 21:42:06,307 (9372) | Listener | debug | Terminating instance socket
2023-10-17 21:42:06,307 (9372) | gridplayer.utils.single_instance | debug | Sending data to running instance: None
2023-10-17 21:42:12,396 (1544) | ENV | INFO | GridPlayer v.0.5.3 starting
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | Environment info
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | ========
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | OS: Windows-10-10.0.19045-SP0
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | OS Ver: 10.0.19045
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | OS Release: 10
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | Python: 3.8.10
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | Qt: 5.15.2
2023-10-17 21:42:12,459 (1544) | ENV | DEBUG | MP Start method: spawn
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | is_pyinstaller_frozen: True
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | _MEIPASS: C:\Program Files\GridPlayer
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | is_flatpak: False
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | is_snap: False
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | is_appimage: False
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | sys.argv: ['C:\\Program Files\\GridPlayer\\GridPlayer.exe']
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | sys.executable: C:\Program Files\GridPlayer\GridPlayer.exe
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | sys.path: ['C:\\Program Files\\GridPlayer\\base_library.zip', 'C:\\Program Files\\GridPlayer\\lib-dynload', 'C:\\Program Files\\GridPlayer']
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | os.getcwd: C:\Program Files\GridPlayer
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | QT Styles: ['windowsvista', 'Windows', 'Fusion']
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | ========
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | ENV
 'ALLUSERSPROFILE': 'C:\\ProgramData',
 'APPDATA': 'C:\\Users\\Asus\\AppData\\Roaming',
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
 'COMPUTERNAME': 'DESKTOP-303SD9S',
 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
 'HOMEDRIVE': 'C:',
 'HOMEPATH': '\\Users\\Asus',
 'LOCALAPPDATA': 'C:\\Users\\Asus\\AppData\\Local',
 'LOGONSERVER': '\\\\DESKTOP-303SD9S',
 'NUMBER_OF_PROCESSORS': '4',
 'ONEDRIVE': 'C:\\Users\\Asus\\OneDrive',
 'OS': 'Windows_NT',
 'PATH': 'C:\\Program Files\\GridPlayer\\PyQt5\\Qt5\\bin;C:\\Program '
         'Files\\GridPlayer;C:\\Program Files (x86)\\Intel\\iCLS '
         'Client\\;C:\\Program Files\\Intel\\iCLS '
         'Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program '
         'Files (x86)\\Intel\\Intel(R) Management Engine '
         'Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine '
         'Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management '
         'Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management '
         'Engine '
         'Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program '
         'Files\\dotnet\\;C:\\Users\\Asus\\AppData\\Local\\Microsoft\\WindowsApps;',
 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
 'PROCESSOR_ARCHITECTURE': 'AMD64',
 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 78 Stepping 3, GenuineIntel',
 'PROCESSOR_LEVEL': '6',
 'PROCESSOR_REVISION': '4e03',
 'PROGRAMDATA': 'C:\\ProgramData',
 'PROGRAMFILES': 'C:\\Program Files',
 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
 'PROGRAMW6432': 'C:\\Program Files',
 'PSMODULEPATH': 'C:\\Program '
                 'Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
 'PUBLIC': 'C:\\Users\\Public',
 'QML2_IMPORT_PATH': 'C:\\Program Files\\GridPlayer\\PyQt5\\Qt5\\qml',
 'QT_PLUGIN_PATH': 'C:\\Program Files\\GridPlayer\\PyQt5\\Qt5\\plugins',
 'SESSIONNAME': 'Console',
 'SYSTEMDRIVE': 'C:',
 'SYSTEMROOT': 'C:\\WINDOWS',
 'TEMP': 'C:\\Users\\Asus\\AppData\\Local\\Temp',
 'TMP': 'C:\\Users\\Asus\\AppData\\Local\\Temp',
 'USERDOMAIN': 'DESKTOP-303SD9S',
 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-303SD9S',
 'USERNAME': 'Asus',
 'USERPROFILE': 'C:\\Users\\Asus',
 'WINDIR': 'C:\\WINDOWS'
2023-10-17 21:42:12,474 (1544) | ENV | DEBUG | ========
2023-10-17 21:42:12,521 (1544) | gridplayer.main.init_translator | DEBUG | Loading translation for fr_FR
2023-10-17 21:42:12,521 (1544) | gridplayer.main.init_translator | DEBUG | QT translations path: C:\Program Files\GridPlayer\PyQt5\Qt5\translations
2023-10-17 21:42:12,521 (1544) | gridplayer.utils.libvlc | DEBUG | Setting paths for embedded VLC
2023-10-17 21:42:12,521 (1544) | gridplayer.utils.libvlc | DEBUG | PYTHON_VLC_MODULE_PATH: C:\Program Files\GridPlayer\libVLC\plugins
2023-10-17 21:42:12,521 (1544) | gridplayer.utils.libvlc | DEBUG | PYTHON_VLC_LIB_PATH: C:\Program Files\GridPlayer\libVLC\libvlc.dll
2023-10-17 21:42:12,537 (1544) | gridplayer.utils.libvlc | DEBUG | VLC initialized paths
2023-10-17 21:42:12,537 (1544) | gridplayer.utils.libvlc | DEBUG | VLC plugin_path: C:\Program Files\GridPlayer\libVLC\plugins
2023-10-17 21:42:12,537 (1544) | gridplayer.utils.libvlc | DEBUG | VLC dll: <PyInstallerCDLL 'C:\Program Files\GridPlayer\libVLC\libvlc.dll', handle 7ffd81710000 at 0x6022910>
2023-10-17 21:42:12,537 (1544) | gridplayer.utils.libvlc | DEBUG | python-vlc 3.0.11115
2023-10-17 21:42:12,537 (1544) | gridplayer.utils.libvlc | DEBUG | VLC 3.0.17.4
2023-10-17 21:42:13,458 (1544) | Listener | debug | Instance socket listening at \\.\pipe\gridplayer-fileopen
2023-10-17 21:42:26,472 (1544) | VideoBlock | debug | vlc_options: []
2023-10-17 21:42:26,503 (1544) | ProcessManagerVLC | debug | Launching process 0816a3a41ce6891c
2023-10-17 21:42:27,207 (6656) | InstanceProcess | DEBUG | Starting process...
2023-10-17 21:42:27,212 (6656) | Settings | DEBUG | Settings path: C:\Users\Asus\AppData\Roaming\vzhd1701\GridPlayer\settings.ini
2023-10-17 21:42:27,212 (6656) | VLC | DEBUG | VLC init options: ['--quiet', '--no-disable-screensaver', '--no-sub-autodetect-file', '--no-lua', '--no-osd', '--no-snapshot-preview', '--no-spu', '--no-interact', '--no-stats', '--no-keyboard-events', '--no-mouse-events']
2023-10-17 21:42:27,213 (6656) | VLC | DEBUG | Using plugin cache
2023-10-17 21:42:28,382 (1544) | urllib3.connectionpool | debug | Starting new HTTPS connection (1): my.mail.ru:443
2023-10-17 21:42:29,543 (1544) | urllib3.connectionpool | debug | https://my.mail.ru:443 "HEAD /v/sienduk/video/35/707.html HTTP/1.1" 200 0
2023-10-17 21:42:29,545 (1544) | VideoURLResolverWorker | debug | Trying to resolve URL with YoutubeDLResolver
2023-10-17 21:42:29,736 (1544) | YoutubeDLResolver | debug | [mailru] Extracting URL: https://my.mail.ru/v/sienduk/video/35/707.html
2023-10-17 21:42:29,737 (1544) | YoutubeDLResolver | debug | [mailru] v/sienduk/35/707: Downloading webpage
2023-10-17 21:42:30,761 (1544) | YoutubeDLResolver | debug | [mailru] v/sienduk/35/707: Downloading video meta JSON
2023-10-17 21:42:31,340 (1544) | YoutubeDLResolver | debug | yt-dlp - 2 stream(s) found
2023-10-17 21:42:32,319 (1544) | urllib3.connectionpool | debug | Starting new HTTP connection (1): cdn59.my.mail.ru:80
2023-10-17 21:42:32,599 (1544) | urllib3.connectionpool | debug | http://cdn59.my.mail.ru:80 "GET /hv/73478144.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2F10.146.243.1%3A8003%2Frados3%2F73478144-hv&p=f&expire_at=1697587200&touch=1637861346&reg=216&sign=1161dd030875f64b2f643b12d4e040eb426d02c7 HTTP/1.1" 403 0
2023-10-17 21:42:32,601 (1544) | VideoURLResolverWorker | error | URL resolver exception
Traceback (most recent call last):
  File "gridplayer\utils\url_resolve\url_resolve.py", line 51, in resolve
  File "gridplayer\utils\url_resolve\url_resolve.py", line 71, in resolve_url
  File "gridplayer\utils\url_resolve\resolver_base.py", line 41, in resolve
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 57, in streams
  File "functools.py", line 967, in __get__
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 45, in is_live
  File "gridplayer\utils\url_resolve\stream_detect.py", line 56, in is_http_live_stream
  File "streamlink\plugin\api\http_session.py", line 190, in request
streamlink.exceptions.PluginError: Unable to open URL: http://cdn59.my.mail.ru/hv/73478144.mp4?slave[]=s%3Ahttp%3A%2F%2F10.146.243.1%3A8003%2Frados3%2F73478144-hv&p=f&expire_at=1697587200&touch=1637861346&reg=216&sign=1161dd030875f64b2f643b12d4e040eb426d02c7 (403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/73478144.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2F10.146.243.1%3A8003%2Frados3%2F73478144-hv&p=f&expire_at=1697587200&touch=1637861346&reg=216&sign=1161dd030875f64b2f643b12d4e040eb426d02c7)
2023-10-17 21:42:32,659 (1544) | VideoBlock | debug | d97aee843abaf4f0: cleaning up resolver
2023-10-17 21:42:32,662 (1544) | VideoBlock | debug | d97aee843abaf4f0: cleaning up driver 
2023-10-17 21:42:32,663 (1544) | VideoBlock | debug | d97aee843abaf4f0: cleaning up done
2023-10-17 21:42:32,663 (6656) | EventWaiter | DEBUG | Aborting waiter
2023-10-17 21:42:32,663 (6656) | PlayerProcessSingleVLCHW | DEBUG | Releasing playlist player
2023-10-17 21:42:32,664 (6656) | PlayerProcessSingleVLCHW | DEBUG | Playlist player released
2023-10-17 21:42:32,664 (6656) | PlayerProcessSingleVLCHW | DEBUG | Releasing player
2023-10-17 21:42:32,665 (6656) | PlayerProcessSingleVLCHW | DEBUG | Player released
2023-10-17 21:42:32,671 (6656) | InstanceProcess | DEBUG | Terminating process...
2023-10-17 21:43:20,147 (1544) | SettingsDialog | debug | Opening log file C:\Users\Asus\AppData\Roaming\vzhd1701\GridPlayer\gridplayer.log
2023-10-17 21:44:00,221 (1544) | VideoBlock | debug | Closing video block d97aee843abaf4f0
2023-10-17 21:44:00,221 (1544) | VideoBlock | debug | d97aee843abaf4f0: cleaning up resolver
2023-10-17 21:44:00,221 (1544) | VideoBlock | debug | d97aee843abaf4f0: cleaning up driver 
2023-10-17 21:44:00,221 (1544) | VideoBlock | debug | d97aee843abaf4f0: cleaning up done
2023-10-17 21:44:00,221 (1544) | VideoBlocksManager | debug | Clearing video blocks array
2023-10-17 21:44:00,221 (1544) | Listener | debug | Terminating instance socket
2023-10-17 21:44:00,221 (1544) | gridplayer.utils.single_instance | debug | Sending data to running instance: None
2023-10-17 21:47:27,259 (9524) | ENV | INFO | GridPlayer v.0.5.3 starting
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | Environment info
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | ========
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | OS: Windows-10-10.0.19045-SP0
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | OS Ver: 10.0.19045
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | OS Release: 10
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | Python: 3.8.10
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | Qt: 5.15.2
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | MP Start method: spawn
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | is_pyinstaller_frozen: True
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | _MEIPASS: C:\Program Files\GridPlayer
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | is_flatpak: False
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | is_snap: False
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | is_appimage: False
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | sys.argv: ['C:\\Program Files\\GridPlayer\\GridPlayer.exe']
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | sys.executable: C:\Program Files\GridPlayer\GridPlayer.exe
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | sys.path: ['C:\\Program Files\\GridPlayer\\base_library.zip', 'C:\\Program Files\\GridPlayer\\lib-dynload', 'C:\\Program Files\\GridPlayer']
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | os.getcwd: C:\Program Files\GridPlayer
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | QT Styles: ['windowsvista', 'Windows', 'Fusion']
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | ========
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | ENV
 'ALLUSERSPROFILE': 'C:\\ProgramData',
 'APPDATA': 'C:\\Users\\Asus\\AppData\\Roaming',
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
 'COMPUTERNAME': 'DESKTOP-303SD9S',
 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
 'HOMEDRIVE': 'C:',
 'HOMEPATH': '\\Users\\Asus',
 'LOCALAPPDATA': 'C:\\Users\\Asus\\AppData\\Local',
 'LOGONSERVER': '\\\\DESKTOP-303SD9S',
 'NUMBER_OF_PROCESSORS': '4',
 'ONEDRIVE': 'C:\\Users\\Asus\\OneDrive',
 'OS': 'Windows_NT',
 'PATH': 'C:\\Program Files\\GridPlayer\\PyQt5\\Qt5\\bin;C:\\Program '
         'Files\\GridPlayer;C:\\Program Files (x86)\\Intel\\iCLS '
         'Client\\;C:\\Program Files\\Intel\\iCLS '
         'Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program '
         'Files (x86)\\Intel\\Intel(R) Management Engine '
         'Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine '
         'Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management '
         'Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management '
         'Engine '
         'Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program '
         'Files\\dotnet\\;C:\\Users\\Asus\\AppData\\Local\\Microsoft\\WindowsApps;',
 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
 'PROCESSOR_ARCHITECTURE': 'AMD64',
 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 78 Stepping 3, GenuineIntel',
 'PROCESSOR_LEVEL': '6',
 'PROCESSOR_REVISION': '4e03',
 'PROGRAMDATA': 'C:\\ProgramData',
 'PROGRAMFILES': 'C:\\Program Files',
 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
 'PROGRAMW6432': 'C:\\Program Files',
 'PSMODULEPATH': 'C:\\Program '
                 'Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
 'PUBLIC': 'C:\\Users\\Public',
 'QML2_IMPORT_PATH': 'C:\\Program Files\\GridPlayer\\PyQt5\\Qt5\\qml',
 'QT_PLUGIN_PATH': 'C:\\Program Files\\GridPlayer\\PyQt5\\Qt5\\plugins',
 'SESSIONNAME': 'Console',
 'SYSTEMDRIVE': 'C:',
 'SYSTEMROOT': 'C:\\WINDOWS',
 'TEMP': 'C:\\Users\\Asus\\AppData\\Local\\Temp',
 'TMP': 'C:\\Users\\Asus\\AppData\\Local\\Temp',
 'USERDOMAIN': 'DESKTOP-303SD9S',
 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-303SD9S',
 'USERNAME': 'Asus',
 'USERPROFILE': 'C:\\Users\\Asus',
 'WINDIR': 'C:\\WINDOWS'
2023-10-17 21:47:27,344 (9524) | ENV | DEBUG | ========
2023-10-17 21:47:27,406 (9524) | gridplayer.main.init_translator | DEBUG | Loading translation for fr_FR
2023-10-17 21:47:27,406 (9524) | gridplayer.main.init_translator | DEBUG | QT translations path: C:\Program Files\GridPlayer\PyQt5\Qt5\translations
2023-10-17 21:47:27,406 (9524) | gridplayer.utils.libvlc | DEBUG | Setting paths for embedded VLC
2023-10-17 21:47:27,406 (9524) | gridplayer.utils.libvlc | DEBUG | PYTHON_VLC_MODULE_PATH: C:\Program Files\GridPlayer\libVLC\plugins
2023-10-17 21:47:27,406 (9524) | gridplayer.utils.libvlc | DEBUG | PYTHON_VLC_LIB_PATH: C:\Program Files\GridPlayer\libVLC\libvlc.dll
2023-10-17 21:47:27,422 (9524) | gridplayer.utils.libvlc | DEBUG | VLC initialized paths
2023-10-17 21:47:27,422 (9524) | gridplayer.utils.libvlc | DEBUG | VLC plugin_path: C:\Program Files\GridPlayer\libVLC\plugins
2023-10-17 21:47:27,422 (9524) | gridplayer.utils.libvlc | DEBUG | VLC dll: <PyInstallerCDLL 'C:\Program Files\GridPlayer\libVLC\libvlc.dll', handle 7ffd81710000 at 0x6032910>
2023-10-17 21:47:27,422 (9524) | gridplayer.utils.libvlc | DEBUG | python-vlc 3.0.11115
2023-10-17 21:47:27,422 (9524) | gridplayer.utils.libvlc | DEBUG | VLC 3.0.17.4
2023-10-17 21:47:28,382 (9524) | Listener | debug | Instance socket listening at \\.\pipe\gridplayer-fileopen
2023-10-17 21:47:45,480 (9524) | SettingsDialog | debug | Opening log file C:\Users\Asus\AppData\Roaming\vzhd1701\GridPlayer\gridplayer.log
2023-10-17 21:56:26,094 (9524) | SettingsDialog | debug | Opening log file C:\Users\Asus\AppData\Roaming\vzhd1701\GridPlayer\gridplayer.log
```

**Comment by trimechee** [comment]
Hello, i don't know if it can help.... today the new version of QMPLAY2 media player has been published and the developer solved the problem of video playback from the site https://my.mail.ru/.....

https://github.com/zaps166/QMPlay2/releases/tag/23.10.22
