### ISSUE TITLE
[Bug]: Media parse failed

### ISSUE THREAD

**Issue by joshinils** [vzhd1701/gridplayer#195]
### GridPlayer version

0.5.2

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 22.04.3

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

Tried to play an MKV file created by makemkv from a DVD.
I tried to open it via right click, add, add file, browse to it and open.

drag and drop for the same file does not crash, but it shows "Media parse failed" and the console shows:
```log
2023-12-10 13:07:03,942 (27083) | QT | WARNING | Qt: Session management error: Could not open network socket
2023-12-10 13:07:07,247 (27179) | PlayerProcessSingleVLCSW | error | Media parse failed
```

VLC is able to play the file just fine.

<details>
<summary>Mediainfo</summary>

```
General
Unique ID                                : 47884416335218612738026236482110543225 (0x240634004246562FCCD4D6107B22D579)
Complete name                            : B1_orig-03_t00.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 3.36 GiB
Duration                                 : 1 h 54 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 4 183 kb/s
Encoded date                             : UTC 2023-12-09 19:11:02
Writing application                      : MakeMKV v1.17.5 linux(x64-release)
Writing library                          : libmakemkv v1.17.5 (1.3.10/1.5.2) x86_64-linux-gnu

Video
ID                                       : 1
ID in the original source medium         : 224 (0xE0)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Format settings, picture structure       : Frame
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 1 h 54 min
Bit rate mode                            : Variable
Bit rate                                 : 3 503 kb/s
Maximum bit rate                         : 9 800 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.338
Time code of first frame                 : 10:00:23:00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open
GOP, Open/Closed of first frame          : Closed
Stream size                              : 2.81 GiB (84%)
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : DVD-Video

Audio #1
ID                                       : 2
ID in the original source medium         : 189 (0xBD)128 (0x80)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 54 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 368 MiB (11%)
Title                                    : Surround 5.1
Language                                 : German
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Original source medium                   : DVD-Video

Audio #2
ID                                       : 3
ID in the original source medium         : 189 (0xBD)129 (0x81)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 54 min
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 184 MiB (5%)
Title                                    : Stereo
Language                                 : German
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : DVD-Video

Text
ID                                       : 4
ID in the original source medium         : 189 (0xBD)32 (0x20)
Format                                   : VobSub
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Duration                                 : 1 h 47 min
Bit rate                                 : 3 047 b/s
Count of elements                        : 1052
Stream size                              : 2.34 MiB (0%)
Language                                 : German
Default                                  : Yes
Forced                                   : No
Original source medium                   : DVD-Video

Menu
00:00:00.000                             : en:Chapter 01
00:08:32.880                             : en:Chapter 02
00:14:00.280                             : en:Chapter 03
00:21:26.280                             : en:Chapter 04
00:35:08.120                             : en:Chapter 05
00:45:26.480                             : en:Chapter 06
00:56:18.680                             : en:Chapter 07
01:09:03.920                             : en:Chapter 08
01:20:31.520                             : en:Chapter 09
01:29:59.360                             : en:Chapter 10
01:38:24.000                             : en:Chapter 11
01:45:13.520                             : en:Chapter 12
```
</details>

### Log excerpt

```shell
Traceback (most recent call last):
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/player/managers/video_driver.py", line 80, in crash
    raise PlayerException(traceback_txt)
gridplayer.exceptions.PlayerException: Exception in thread
Thread-8 (cmd_loop_thread_func)
Traceback (most recent call last):
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/multiprocess/command_loop.py", line 65, in cmd_loop_thread_func
    self.cmd_loop_thread_body()
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/multiprocess/command_loop.py", line 81, in cmd_loop_thread_body
    self.cmd_loop_run()
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/multiprocess/command_loop.py", line 25, in cmd_loop_run
    self.cmd_process_command(command_args, command_name)
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/multiprocess/command_loop.py", line 33, in cmd_process_command
    func(*command_args)
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/widgets/video_frame_vlc_sw.py", line 114, in load_video_st2_set_media
    self._init_video_decoder()
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/widgets/video_frame_vlc_sw.py", line 147, in _init_video_decoder
    self.decoder.set_frame(width, height)
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/vlc_player/image_decoder.py", line 40, in set_frame
    self._shared_memory.allocate(buf_size)
  File "/snap/gridplayer/19/lib/python3.10/site-packages/gridplayer/multiprocess/safe_shared_memory.py", line 50, in allocate
    self._memory = SharedMemory(name=self.name, create=True, size=size)
  File "/usr/lib/python3.10/multiprocessing/shared_memory.py", line 104, in __init__
    self._fd = _posixshmem.shm_open(
PermissionError: [Errno 13] Permission denied: '/69ec0aacd5a0afbf'
```

**Comment by joshinils** [comment]
Doesn't happen with the version 0.5.3 from flatpak...
