### ISSUE TITLE
Opening program from a CD

### ISSUE THREAD

**Issue by Martinxc** [vzhd1701/gridplayer#224]
### GridPlayer version

0.5.3

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 11 Pro

### What distribution channel are you using? [LINUX ONLY]

None

### Bug description

If program is opened from a CD it generates permission denied. I am assuming its because its trying to save a log file on that CD. In that case it should say in my opinion that log can not be save and open program as usual.

### Log excerpt

```shell
Traceback (most recent call last):
  File "logging\config.py", line 563, in configure
  File "logging\config.py", line 744, in configure_handler
  File "logging\__init__.py", line 1147, in __init__
  File "logging\__init__.py", line 1176, in _open
PermissionError: [Errno 13] Permission denied: 'F:\\GridPlayer\\portable_data\\gridplayer.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gridplayer\__main__.py", line 44, in <module>
  File "gridplayer\__main__.py", line 23, in main
  File "gridplayer\main\init_log.py", line 19, in init_log
  File "gridplayer\utils\log_config.py", line 122, in config_log
  File "logging\config.py", line 808, in dictConfig
  File "logging\config.py", line 570, in configure
ValueError: Unable to configure handler 'file'
```

**Comment by vzhd1701** [comment]
You can't use portable soft from read-only medium
