### ISSUE TITLE
Mail.ru fail and download media data independently from playback if weak connection and increase network cache

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#54]
### GridPlayer version

v0.3.0

### What OS are you using?

Windows

### OS Version / Linux distribution

windows10

### Bug description

Hello, i tried to play this vidéo from mail.ru but Girdplayer failed to resolve url, it will be great if threr is fix please 👍 

https://my.mail.ru/mail/richard1339/video/_myvideo/1041.html?from=videoplayer

and it will be great if Girdplayer add a button  "paste url from clipboard" and option or button to increase network cache to avoid jerks and add this important option to people who have limited 4G data ou weak wifi please , option like the option made by "3DYD Youtube Source" software :

Download media data independently from playback
If this option is checked, filter performs media file download independently of playback. So it continues downloading even when playback is paused.

This approach is useful when you have slow or unstable Internet connection (so playback is stuttering), or when you need to seek a lot within a file. However if all these cases are not about you, and usually you do not watch whole video, it may end up with bandwidth overuse since a lot of downloaded data eventually will be not watched.

When this option is unchecked, filter downloads only part of data that is about to be played.

Filter caches downloaded data in temporary directory regardless of the state of this option and never re-downloads the same data again. Caching is well visualized by Activity

**Comment by trimechee** [comment]
the logs : 

" 2022-06-25 17:11:42,193 (7080) | gridplayer.utils.url_resolve.resolver_yt_dlp | warning | [generic] Falling back on generic information extractor.
2022-06-25 17:11:43,194 (7080) | gridplayer.utils.url_resolve.resolver_yt_dlp | error | ERROR: Unsupported URL: https://wiflix.bet/serie-en-streaming/19929-lattaque-des-titans-saison-4.html
2022-06-25 17:11:44,134 (7080) | gridplayer.utils.url_resolve.url_resolve | error | URL returned html page https://wiflix.bet/serie-en-streaming/19929-lattaque-des-titans-saison-4.html
2022-06-25 17:14:22,542 (7080) | gridplayer.utils.url_resolve.url_resolve | critical | Traceback (most recent call last):
  File "streamlink\plugin\api\http_session.py", line 214, in request
  File "requests\models.py", line 960, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/71099192.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\utils\url_resolve\url_resolve.py", line 31, in resolve
  File "gridplayer\utils\url_resolve\url_resolve.py", line 57, in resolve_url
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 36, in resolve_youtube_dl
  File "gridplayer\utils\url_resolve\stream_detect.py", line 42, in is_http_live_stream
  File "streamlink\plugin\api\http_session.py", line 222, in request
streamlink.exceptions.PluginError: Unable to open URL: http://cdn59.my.mail.ru/hv/71099192.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6 (403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/71099192.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6)

2022-06-25 17:31:10,358 (6212) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 17:31:10,360 (6212) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout
2022-06-25 17:34:57,520 (596) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 17:34:57,525 (596) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout "

**Comment by trimechee** [comment]
"
2022-06-25 17:14:22,542 (7080) | gridplayer.utils.url_resolve.url_resolve | critical | Traceback (most recent call last):
  File "streamlink\plugin\api\http_session.py", line 214, in request
  File "requests\models.py", line 960, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/71099192.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\utils\url_resolve\url_resolve.py", line 31, in resolve
  File "gridplayer\utils\url_resolve\url_resolve.py", line 57, in resolve_url
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 36, in resolve_youtube_dl
  File "gridplayer\utils\url_resolve\stream_detect.py", line 42, in is_http_live_stream
  File "streamlink\plugin\api\http_session.py", line 222, in request
streamlink.exceptions.PluginError: Unable to open URL: http://cdn59.my.mail.ru/hv/71099192.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6 (403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/71099192.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6)

**Comment by vzhd1701** [comment]
This should be fixed now. Please check out the new version.

**Comment by trimechee** [comment]
That's awesome !! Thank you for fixinig this problem :)

**Comment by trimechee** [comment]
And for the another suggestion for the week connection please, it will be great to add add option to increase manully or automatically network cache and option to change quickly the video resolution quality or option to download media data independently from playback, so after after finishing, you can even disconnect from the internet if it's a long and fully loaded video.....or even add an option to download the streaming video with right click.....

Thank you so much :)

**Comment by vzhd1701** [comment]
I'll add setting to control network caching, but I can't promise to add video download function to the player, sorry.

For now you can set network caching by adding `--network-caching` option in Advanced settings. The value is set in milliseconds, so if you want to set cache to 10 seconds, then multiply it by 1000. Maximum value is 60000, which means 60 seconds.

![image](https://user-images.githubusercontent.com/5212766/179178019-32d00cc3-8ffe-408a-aa54-eabd0272f68c.png)

Also you already have a setting to set default streaming quality

![image](https://user-images.githubusercontent.com/5212766/179177132-39be13ad-f846-4172-9f9f-87f18ae650d1.png)

**Comment by trimechee** [comment]
Marvellous ! we are very grateful to you for adding this important option :)
