### ISSUE TITLE
Dailymotion fail 

### ISSUE THREAD

**Issue by trimechee** [vzhd1701/gridplayer#55]
### GridPlayer version

v0.3.0

### What OS are you using?

Windows

### OS Version / Linux distribution

windows 10

### Bug description

Hello, i tried to play dailymotion video but it fails , Girdplayer says "buffering timeout" : 

https://www.dailymotion.com/video/x8bz3a5

**Comment by trimechee** [comment]
the log : 

" 2022-06-25 17:11:42,193 (7080) | gridplayer.utils.url_resolve.resolver_yt_dlp | warning | [generic] Falling back on generic information extractor.
2022-06-25 17:11:43,194 (7080) | gridplayer.utils.url_resolve.resolver_yt_dlp | error | ERROR: Unsupported URL: https://wiflix.bet/serie-en-streaming/19929-lattaque-des-titans-saison-4.html
2022-06-25 17:11:44,134 (7080) | gridplayer.utils.url_resolve.url_resolve | error | URL returned html page https://wiflix.bet/serie-en-streaming/19929-lattaque-des-titans-saison-4.html
2022-06-25 17:14:22,542 (7080) | gridplayer.utils.url_resolve.url_resolve | critical | Traceback (most recent call last):
  File "streamlink\plugin\api\http_session.py", line 214, in request
  File "requests\models.py", line 960, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/71099192.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridplayer\utils\url_resolve\url_resolve.py", line 31, in resolve
  File "gridplayer\utils\url_resolve\url_resolve.py", line 57, in resolve_url
  File "gridplayer\utils\url_resolve\resolver_yt_dlp.py", line 36, in resolve_youtube_dl
  File "gridplayer\utils\url_resolve\stream_detect.py", line 42, in is_http_live_stream
  File "streamlink\plugin\api\http_session.py", line 222, in request
streamlink.exceptions.PluginError: Unable to open URL: http://cdn59.my.mail.ru/hv/71099192.mp4?slave[]=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6 (403 Client Error: Forbidden for url: http://cdn59.my.mail.ru/hv/71099192.mp4?slave%5B%5D=s%3Ahttp%3A%2F%2Fvideo-cephrgw1.i%3A9090%2Fvideo4%2F71099192-hv&p=f&expire_at=1656187200&touch=1604135695&reg=216&sign=de2101b9311adb6b855f9ebdaf949b4f273172f6)

2022-06-25 17:31:10,358 (6212) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 17:31:10,360 (6212) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout
2022-06-25 17:34:57,520 (596) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 17:34:57,525 (596) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout "

**Comment by trimechee** [comment]
Now i tried with another link, 

https://www.dailymotion.com/video/x8bztce?playlist=x5nmbq


that work and i can play dailymotion vidéo ! but i don't why i can't play the other dailymotion link

**Comment by trimechee** [comment]
i tried to play the first link again, i can't : 

"2022-06-25 17:31:10,358 (6212) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 17:31:10,360 (6212) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout
2022-06-25 17:34:57,520 (596) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 17:34:57,525 (596) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout
2022-06-25 19:22:28,277 (1352) | QT | warning | requestActivate() called for  QWidgetWindow(0x4926e10, name="QWidgetClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2022-06-25 19:39:12,528 (3152) | EventWaiter | ERROR | Waiting for buffering timed out after 30 seconds
2022-06-25 19:39:12,529 (3152) | PlayerProcessSingleVLCHW | ERROR | Buffering timeout"

**Comment by vzhd1701** [comment]
This should be fixed now. Please check out the new version and tell if this issue is resolved.

**Comment by trimechee** [comment]
Wonderful !! thank you so much !
